<a href="https://colab.research.google.com/github/nsk31512/terver/blob/linalg_task5/Linalg_HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np

In [42]:
#1
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
U, s, W = np.linalg.svd(A)

V = W.T


D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [43]:
print(f'Матрица U:\n {U}')

Матрица U:
 [[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]


In [44]:
print(f'Матрица D:\n {D}')

Матрица D:
 [[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]


In [45]:
print(f'Матрица V:\n {V}')

Матрица V:
 [[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]


In [46]:
#2
#евклидова норма:
A_e = D[0][0]
A_e

8.824868854820444

In [50]:
#Норма Фробениуса:
sum = 0
for item in s:  
  sum += item**2  
A_f = np.math.sqrt(sum)
A_f

11.045361017187263