<a href="https://colab.research.google.com/github/nsk31512/terver/blob/linalg_task4/%D0%A3%D1%80%D0%BE%D0%BA_4_%D0%94%D0%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Часть 1. Задание 2

In [1]:
import numpy as np

In [16]:
def slau(matrix, matrix_extended):
  #matrix - матрица коэффициентов
  #matrix_extended - расширенная матрица
  #n - число неизвестных

  rank_matrix = np.linalg.matrix_rank(matrix)
  rank_matrix_ext = np.linalg.matrix_rank(matrix_extended)
  n = len(matrix[0])
  
  if rank_matrix == rank_matrix_ext and rank_matrix == n:
    print("Система определена и имеет одно решение")
  elif rank_matrix == rank_matrix_ext and rank_matrix < n:
    print("Система совместна и имеет бесконечно число решений")
  elif rank_matrix < rank_matrix_ext:
    print("Система несовместна")


In [13]:
#2a)
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A_ext = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
slau(A, A_ext)


Система определена и имеет одно решение


In [14]:
#2б)
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A_ext = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, -5]])
slau(A, A_ext)


Система несовместна


In [18]:
#2в)
A = np.array([[1, 2, 5], [3, 1, -8]])
A_ext = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
slau(A, A_ext)

Система совместна и имеет бесконечно число решений


#Часть 1. Задание 3

In [21]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
A_ext = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
slau(A, A_ext)

Система определена и имеет одно решение


#Часть 2. Задание 2*

In [124]:
from scipy.linalg import lu

In [125]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
p, l, u = lu(A)
l

array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.8       , 1.        ]])

In [130]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
p, l, u = lu(A)
l

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.75      , -0.25      ,  1.        ,  0.        ],
       [ 0.25      ,  0.75      , -0.17073171,  1.        ]])

#Часть 2. Задание 5*

Пытался написать код к 5 задаче, но так и не смог найти что не так сделал

In [152]:
def lu_decompose(matrix):
  #U - верхнетрегольная матрица
  #L - нижнетреугольная матрица
  #u - построчный список элементов для заполнения матрицы U
  #l - построчный список элементов для заполнения матрицы L

  U = list()
  L = list()
  for i in range(len(matrix)):
    u = list()
    l = list()
    if i == 0:            
      for j in range(len(matrix)):      
        u.append(matrix[i][j])
        l.append(matrix[j][i]/matrix[0][0])
      U.append(u)
      L.append(l)
    else:
      for j in range(len(matrix)):
        if j == i:
          l.append(1)          
          foo_u = 0
          for k in range(i):            
            foo_u += matrix[i][k]*matrix[k][i]
          u.append(matrix[i][j] - foo_u)
            
        elif j < i:
          u.append(0)
          l.append(0)
          
        elif j > i:                    
          foo_u = 0
          foo_l = 0
          for k in range(i):            
            foo_u += matrix[i][k]*matrix[k][i]
            foo_l += matrix[k][i]*matrix[j][k]
          u.append(matrix[i][j] - foo_u)
          l.append((matrix[j][i] - foo_l)/matrix[0][0])          
      U.append(u)
      L.append(l)
  U = np.array(U)
  L = np.array(L).T
  return U, L


In [154]:
#матрица для проверки кода из методички
A = np.array([[2, 1, -1], [4, -6, -2], [-2, 7, -3]])
lu_decompose(A)
print(U)
print(L)


[[  2   1  -1]
 [  0 -10  -4]
 [  0   0   9]]
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  3.  1.]]
